apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  liveness:
    path: /bidrag-beregn-bidragsevne-rest/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-beregn-bidragsevne-rest/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-beregn-bidragsevne-rest/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress }}
  vault:
    enabled: false
  env:
    - name: SJABLON_URL
      value: {{ sjablonurl }}
  webproxy:
    true

  # only valid configuration for google cloud platform
  accesspolicy:
    outbound:
      rules:
        - application: bidrag-sjablon
